Basic batch
OpenMined/PIR pull request #26
Opened 2020-06-07 19:06 UTC by bcebere

## Description
In order to support PSI, we need an (basic at least) support for batch queries.
fixes https://github.com/OpenMined/PIR/issues/22

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2020-06-09 09:37 UTC, kshehata requested changes
Thanks for jumping into this Bogdan! I think we can simplify a lot of we treat multi-query and single-query with the same message type.

2020-06-09 09:37 UTC, kshehata commented on pir/proto/payload.proto
> +message BatchRequest {
Why create new messages instead of expanding the existing ones? This seems like duplication.

2020-06-09 09:37 UTC, kshehata commented on pir/cpp/client.h
> +  StatusOr<BatchRequest> CreateRequest(
This code would be a lot simpler if CreateRequest() returned the same time in each case, and the single index case was just a wrapper to call the multiple case with a vector of one item.

2020-06-09 09:37 UTC, kshehata commented on pir/cpp/client.h
> +      const BatchResponse& response) const;
Again, I'd make one function that calls the other, and just returns an InvalidArgumentError for the single case if there are too many results.

2020-06-09 09:37 UTC, kshehata commented on pir/cpp/server.h
> +  StatusOr<BatchResponse> ProcessRequest(const BatchRequest& request) const;
This code becomes trivial if they both share the same message type

2020-06-10 05:12 UTC, kshehata reviewed
Looking good Bogdan! Definitely like the way the protobufs and interfaces look now. A few comments, mostly for more minor details. You know that once I'm getting into the details of unit tests that we're almost finished :)

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/serialization.cpp
> +    RETURN_IF_ERROR(SaveCiphertexts(cts[idx], request->add_query()));
Why not call the other function?

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server.cpp
> +  for (int idx = 0; idx < request.query_size(); ++idx) {
How about a foreach here? Might be slightly easier to read.

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server.cpp
> +    RETURN_IF_ERROR(processQuery(request.query(idx), request.galois_keys(),
It would probably be more efficient to parse the galois and relin keys once, and then pass them in every time. We may have thousands of response items.

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server.cpp
> +                                         decltype(dimensions)::value_type(0));
This can also be precomputed.

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +                 .ValueOrDie();
Probably should check that size is 1 before retrieving the value.

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +      LoadCiphertexts(Context()->SEALContext(), request_proto.query(0))
Same here, check that request_proto.query_size() is 1

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +      LoadCiphertexts(Context()->SEALContext(), request_proto.query(0))
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +      LoadCiphertexts(Context()->SEALContext(), request_proto.query(0))
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +      LoadCiphertexts(Context()->SEALContext(), request_proto.query(0))
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +  ASSERT_EQ(result[0], value);
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +  SaveCiphertexts(ct, response.add_reply());
Should these perhaps be different? Avoids error of returning the same value twice?

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/client_test.cpp
> +          EXPECT_EQ(pt[i], 0);
I'm not sure what I was originally thinking here, but this for loop is in the wrong place. It should probably be under the else clause below.

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server_test.cpp
> +  ASSERT_EQ(result[0], db_[desired_index]);
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server_test.cpp
> +                                result_or.ValueOrDie().reply(0))
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server_test.cpp
> +                                result_or.ValueOrDie().reply(0))
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server_test.cpp
> +                                result_or.ValueOrDie().reply(0))
Size check

2020-06-10 05:12 UTC, kshehata commented on pir/cpp/server_test.cpp
> +                                result_or.ValueOrDie().reply(0))
Size check

2020-06-11 08:17 UTC, kshehata approved these changes
LGTM Bogdan! Good work on this - it's a very clean approach. I've left some comments, but they're all pretty minor. You're good to merge this when you're ready.

2020-06-11 08:17 UTC, kshehata commented on pir/cpp/server.cpp
> +  if (!relin_keys) {
nit: doing this in the opposite order is slightly more readable. i.e. "if you have relin keys, use them, if not then go without them." The opposite is more complicated: "if you don't have relin keys, then don't use them, but other wise use them"

2020-06-11 08:17 UTC, kshehata commented on pir/cpp/server.cpp
> +  for (auto& query : request.query()) {
const?

2020-06-11 08:17 UTC, kshehata commented on pir/cpp/client.cpp
> +  for (size_t idx = 0; idx < indexes.size(); ++idx) {
Just out of curiosity: why idx instead of i here?

2020-06-11 08:17 UTC, kshehata commented on pir/cpp/client.cpp
> +      // than number of items in oblivious expansion.
This is no longer true. I'd meant to remove this earlier. Would you mind just taking it out here?

2020-06-11 08:17 UTC, kshehata commented on pir/cpp/client.cpp
> +StatusOr<std::vector<int64_t>> PIRClient::ProcessResponse(
Suggestion: If you move ProcessResponse to after createQueryFor, it'll make the diff cleaner and make it easier to follow the code.

2020-06-11 08:17 UTC, kshehata commented on pir/cpp/serialization.cpp
> +  for (size_t idx = 0; idx < cts.size(); ++idx) {
foreach?

2020-06-11 08:17 UTC, kshehata commented on pir/cpp/client_test.cpp
> +  const vector<size_t> indexes = {desired_index};
nit: indices is the more correct term here. So long as you're consistent as you are here, it should be fine.

2020-06-11 09:52 UTC, bcebere commented on pir/cpp/client.cpp
> +  for (size_t idx = 0; idx < indexes.size(); ++idx) {
No reason

2020-06-11 09:53 UTC, merged